name: "Deploy to github pages"

on:
  push:
    branches:
      - "feature/feature_branch"

jobs:
  testPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test
      - name: Reset promotion branch
        run: |
          git fetch origin feature/feature_branch:feature/feature_branch
          git reset --hard feature/feature_branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test-promotion